blog/applications/entry/urls.py
from django.urls import path
from . import views


app_name = "entry_app"

urlpatterns = [
    path('inputs/', views.EntryListView.as_view(), name='entry'), 
    path('detail-inputs/<slug>/', views.EntryDetailView.as_view(), name='detail_inputs')
]

blog/applications/favorite/urls.py
from django.urls import path
from . import views


app_name = "favorite_app"

urlpatterns = [
    path('profile/', views.UserPageListView.as_view(), name='profile'),
    # le pasamos un pk porque estamos recuperandolo en el entry= Entry.objects.get(id=self.kwargs['pk'])
    path('Add-entry/<pk>/',views.AddFavoriteView.as_view(), name='favorite_add'),
    path('delete-favorite/<pk>/', views.FavoriteDeleteView.as_view(), name='favorite_delete'),   
]

    

blog/applications/home/urls.py
from django.urls import path
from . import views

app_name = "home_app"

urlpatterns = [
    path('',views.HomePageView.as_view(),name='index'), 
    path('register-suscriber/',views.SuscriberCreateView.as_view(), name='add_suscriber'),
    path('form-contact/', views.ContactCreateView.as_view(), name='form_contact'),
]

blog/applications/users/urls.py
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(),name='user_register'),
    path('login/',views.LoginUser.as_view(),name='user_login'),
    path('logout/',views.LogoutView.as_view(),name='user_logout'),
    path('update/',views.UpdatePasswordView.as_view(),name='user_update'),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
# Seo
from django.contrib.sitemaps.views import sitemap
from applications.home.sitemap import EntrySitemap, Sitemap

urlpatterns_main = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.entry.urls')),
    re_path('', include('applications.favorite.urls')),
    # url for ckeditor
    re_path(r'^ckeditor/',include('ckeditor_uploader.urls')),
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# site map object that generates xml
sitemaps={
    # url root
    'site':Sitemap(
        ['home_app:index']
    ),
    'entries': EntrySitemap

}

urlpatterns_sitemap=[
    path('sitemap.xml', sitemap,{'sitemaps':sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

# we concatenate the urlpatterns because it is the one who reads the urls.py
urlpatterns = urlpatterns_main + urlpatterns_sitemap

blog/templates/includes/footer.html
<div class="callout secondary">
    <div class="grid-x align-center">
        <h3 class="cell small-12 large-7">Contact Form:</h3>
        <form class="cell small-12 large-7" method="POST" action="{% url 'home_app:form_contact' %}"> {% csrf_token %}
            <div class="grid-x grid-padding-x">
                <div class="medium-6 cell">
                  <label>First name 
                    <input type="text" name="first_name" id="id_first_name" placeholder="First name">
                  </label>
                </div>
                <div class="medium-6 cell">
                  <label>Last name 
                    <input type="text" name="last_name" id="id_last_name" placeholder="Last name">
                  </label>
                </div>
                <div class="medium-12 cell">
                  <label>Email address
                    <input type="email" name="email" id="id_email" placeholder="Email">
                  </label>
                </div>
                <div class="medium-12 cell">
                    <label>Message
                        <textarea name="message" id="id_message" placeholder="Message"></textarea>
                    </label>
                </div>
                <div class="medium-12 cell">
                    <button type="submit" class="success button">Send</button>
                </div>
            </div>
        </form>
        <p class="cell large-8 ">Other forms of contact:</p>
        <p class="cell large-8"> 
          <span class="label warning">{{ other_email }}</span>
          <span class="label warning">{{ phone }}</span>
        </p>
    </div>
</div>

blog/templates/includes/header.html
<header>
    <div class="grid-x grid-margin-x header" style="background-color: #222222;">
        <div class="cell small-12 medium-4 large-3">
            <a href="{% url 'home_app:index' %}" style="font-size: 20px; color: #0277bd;">
                Neldis Blog
            </a>
        </div>
        <div class="cell small-12 medium-4">
            
        </div>
        <div class="cell small-12 large-5">
            <ul class="menu" style="justify-content: flex-end;">
                <li>
                    <a href="{% url 'home_app:index' %}">Home</a>
                </li>
                <li>
                    <a href="{% url 'entry_app:entry' %}">Blog</a>
                </li>
                <li>
                    {% if not user.is_anonymous %}
                        <a href="{% url 'favorite_app:profile' %}" class="warning button">Profile</a>
                    {% else %}
                        <a href="{% url 'users_app:user_login' %}" class="primary button">Access</a>
                    {% endif %}
                        
                </li>
            </ul>
        </div>
    </div>
</header>