blog/applications/entry/urls.py
from django.urls import path
from . import views


app_name = "entry_app"

urlpatterns = [
    path('inputs/', views.EntryListView.as_view(), name='entry'), 
    path('detail-inputs/<slug>/', views.EntryDetailView.as_view(), name='detail_inputs')
]

blog/applications/favorite/urls.py
from django.urls import path
from . import views


app_name = "favorite_app"

urlpatterns = [
    path('profile/', views.UserPageListView.as_view(), name='profile'),
    # le pasamos un pk porque estamos recuperandolo en el entry= Entry.objects.get(id=self.kwargs['pk'])
    path('Add-entry/<pk>/',views.AddFavoriteView.as_view(), name='favorite_add'),
    path('delete-favorite/<pk>/', views.FavoriteDeleteView.as_view(), name='favorite_delete'),   
]

    

blog/applications/users/urls.py
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(),name='user_register'),
    path('login/',views.LoginUser.as_view(),name='user_login'),
    path('logout/',views.LogoutView.as_view(),name='user_logout'),
    path('update/',views.UpdatePasswordView.as_view(),name='user_update'),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
# Seo
from django.contrib.sitemaps.views import sitemap
from applications.home.sitemap import EntrySitemap, Sitemap

urlpatterns_main = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.entry.urls')),
    re_path('', include('applications.favorite.urls')),
    # url for ckeditor
    re_path(r'^ckeditor/',include('ckeditor_uploader.urls')),
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# site map object that generates xml
sitemaps={
    # url root
    'site':Sitemap(
        ['home_app:index']
    ),
    'entries': EntrySitemap

}

urlpatterns_sitemap=[
    path('sitemap.xml', sitemap,{'sitemaps':sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

# we concatenate the urlpatterns because it is the one who reads the urls.py
urlpatterns = urlpatterns_main + urlpatterns_sitemap

blog/applications/favorite/models.py
from django.db import models
from django.conf import settings
#app third party
from model_utils.models import TimeStampedModel 
#
from applications.entry.models import Entry
from .managers import FavoritesManager

class Favorites(TimeStampedModel):
    user=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,related_name='user_favorites')
    entry= models.ForeignKey(Entry,on_delete=models.CASCADE, related_name='entry_favorites')

    objects= FavoritesManager()

    class Meta:
        # para que se guarde la entrada de favoritos una sola vez y no que se guarde la misma varias veces
        unique_together=('user','entry')
        verbose_name= 'Favorite entry'
        verbose_name_plural='Favorite entries'

    def __str__(self):
        return self.user

blog/applications/favorite/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
# solo para usuarios logeados
from django.contrib.auth.mixins import LoginRequiredMixin 

from django.views.generic import View, ListView, DeleteView

from .models import Favorites
from applications.entry.models import Entry

class UserPageListView(LoginRequiredMixin,ListView):
    template_name = "favorite/profile.html"
    context_object_name= 'entry_user'
    login_url= reverse_lazy('users_app:user_login')

    def get_queryset(self):
        
        return Favorites.objects.entry_user(self.request.user) # esto trae el usuario activo de la sesion


class AddFavoriteView( LoginRequiredMixin, View):
    login_url= reverse_lazy('users_app:user_login')

    def post(self,request, *args, **kwargs):
        # recuperar un usuario
        userr= self.request.user
        entries= Entry.objects.get(id=self.kwargs['pk'])
        # registramos favorito
        Favorites.objects.create(
            user=userr,
            entry= entries,
        )
        return HttpResponseRedirect(
            reverse('favorite_app:profile',)
        )


class FavoriteDeleteView(DeleteView):
    model = Favorites
    success_url= reverse_lazy('favorite_app:profile')

blog/templates/favorite/base_favorite.html
{% extends "base.html" %}

{% load  static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/myblog.css' %}">
{% endblock css %}

{% block js %}

{% endblock js %}

blog/templates/favorite/profile.html
<!-- head para PC -->
{% extends "favorite/base_favorite.html" %}
{% load  static %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x grid-margin-x align-center" style="margin-top: 1em;">
        <!-- bloque de datos de usuario -->
        <div class="cell small-12 large-4">
            <div class="callout">
                <h5>{{ user.full_name }}</h5>
                <p>{{ user.email }} - {{ user.ocupation }} - {{ user.date_birth }}</p>
                <a href="#">Edit data</a>
                <p>
                    <a href="{% url 'users_app:user_logout' %}" class="clear button secondary pd-5">Exit</a>
                </p>
            </div>
        </div>
        <!-- FIN bloque de datos de usuario -->

        <!-- bloque de articulos favoritos de usuario -->
        <div class="cell large-8 grid-x grid-margin-x align-center">
            
            {% for entrys in entry_user %} <!-- el entry_user viene del context_object_name-->       
                <div class="cell small-12">
                    <div class="card-favoritos">
                        <img class="card-favoritos-img" src="{{ entrys.entry.image.url }}">
                        <div class="card-favoritos-body">
                            <h3 class="card-favoritos-body-titulo">{{ entrys.entry.title }}</h3>
                            <p class="card-favoritos-body-text">{{ entrys.entry.summary | truncatechars:70 }}</p>
                            <form class="card-favoritos-body-actions" method="POST" action="{% url 'favorite_app:favorite_delete' entrys.id %}">
                                {% csrf_token %}
                                <a class="button warning" href="{% url 'entry_app:detail_inputs' entrys.entry.slug %}">See</a>
                                <button type="submit" class="button alert">Delete</button>
                            </form>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <!-- FIN bloque de articulos favoritos de usuario --> 
    </div>  
</div>
{% include "includes/footer.html" %}

{% endblock content %}