blog/applications/entry/urls.py
from django.urls import path
from . import views


app_name = "entry_app"

urlpatterns = [
    path('inputs/', views.EntryListView.as_view(), name='entry'), 
    path('detail-inputs/<slug>/', views.EntryDetailView.as_view(), name='detail_inputs')
]

blog/applications/home/urls.py
from django.urls import path
from . import views

app_name = "home_app"

urlpatterns = [
    path('',views.HomePageView.as_view(),name='index'), 
    path('register-suscriber/',views.SuscriberCreateView.as_view(), name='add_suscriber'),
    path('form-contact/', views.ContactCreateView.as_view(), name='form_contact'),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
# Seo
from django.contrib.sitemaps.views import sitemap
from applications.home.sitemap import EntrySitemap, Sitemap

urlpatterns_main = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.entry.urls')),
    re_path('', include('applications.favorite.urls')),
    # url for ckeditor
    re_path(r'^ckeditor/',include('ckeditor_uploader.urls')),
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# site map object that generates xml
sitemaps={
    # url root
    'site':Sitemap(
        ['home_app:index']
    ),
    'entries': EntrySitemap

}

urlpatterns_sitemap=[
    path('sitemap.xml', sitemap,{'sitemaps':sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

# we concatenate the urlpatterns because it is the one who reads the urls.py
urlpatterns = urlpatterns_main + urlpatterns_sitemap

blog/applications/home/models.py
from django.db import models
#app third party
from model_utils.models import TimeStampedModel

class Home(TimeStampedModel):
    title = models.CharField('Name', max_length=30)
    description = models.TextField()
    about_title = models.CharField('Title of us', max_length=50)
    about_text = models.TextField()
    contact_email = models.EmailField('Contact email', blank=True, null=True)
    phone_number= models.CharField('Contact phone',max_length=20)

    class Meta:
        verbose_name= 'Homepage'
        verbose_name_plural='Homepage'

    def __str__(self):
        return self.title


class Suscribers(TimeStampedModel):
    email= models.EmailField('Name', max_length=60)

    class Meta:
        verbose_name='Suscriber'
        verbose_name_plural='Suscribers'

    def __str__(self):
        return self.email


class Contact(TimeStampedModel):
    first_name = models.CharField('First name', max_length=40)
    last_name= models.CharField('Last name', max_length= 40)
    email= models.EmailField()
    message = models.TextField()

    class Meta:
        verbose_name='Contact'
        verbose_name_plural='Contacts'

    def __str__(self):
        return self.first_name + ' ' + self.last_name

blog/applications/home/forms.py
from django import forms

from .models import Suscribers, Contact

class SuscriberForm(forms.ModelForm):
    class Meta:
        model= Suscribers
        fields= (
            'email',
        )
        widgets= {
            'email': forms.EmailInput(
                attrs= {
                    'placeholder':'Email',
                }
            ),
        }


class ContactForm(forms.ModelForm):
    class Meta:
        model= Contact
        fields= ('__all__')

blog/applications/home/views.py
import datetime
#
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse

from django.views.generic import TemplateView, CreateView

from applications.entry.models import Entry
from .models import Home
from .forms import SuscriberForm, ContactForm

#class TestPlantilla(TemplateView):
 #   template_name = "plantillas/register.html"


class HomePageView(TemplateView):
    template_name = "home/index.html"

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        # cargamos home
        # latest recupera el ultimo registro en base a un parametro que le demos, 
        # es este caso le estamos diciendo que lo triaga por la ultima en base a la fecha de creacion('created')
        context['home']= Home.objects.latest('created')
        # contexto de portada
        context['cover_page']= Entry.objects.entry_cover_page()
        # contexto para los articulos en home
        context['entry_home']= Entry.objects.entry_home()
        # entradas recientes
        context['entry_recent']= Entry.objects.entry_recent()
        # Enviamos formulario de suscripcion 
        context['form']= SuscriberForm

        return context
    


class SuscriberCreateView(CreateView):
    form_class= SuscriberForm
    success_url= '.' # se refresque en la misma pagina


class ContactCreateView(CreateView):
    form_class= ContactForm
    success_url= '.'
    

blog/templates/home/base_home.html
{% extends "base.html" %}

{% load  static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/myblog.css' %}">
{% endblock css %}

{% block js %}

{% endblock js %}

blog/templates/home/index.html
<!-- head para PC -->
{% extends "home/base_home.html" %}
{% load  static %}

<!-- home viene del views.py del context['home'] y title del models.py de home-->
{% block title %}
{{ home.title }}  
{% endblock title %}    

{% block description %}
<meta name="description" content="{{ home.description }}"> 
{% endblock description %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <!-- primer bloque del home -->
    <div class="grid-x grid-margin-x" style="margin-top: 1em;">
        <!-- bloque de blog principal -->
        <div class="cell small-12 large-6">
            <div class="card" style="width: 100%;">
                <img src="{{ cover_page.image.url }}">
                <div class="card-section">
                  <h4><a href="{% url 'entry_app:detail_inputs' cover_page.id %}">{{ cover_page.title }}</a></h4>
                  <p>{{ cover_page.summary | truncatechars:100 }}</p>
                </div>
            </div>
        </div>
        <!-- FIN bloque de blog principal -->

        <!-- bloque de blog principal -->
        <div class="cell small-12 large-6 grid-x grid-margin-x">
            
            {% for entry in entry_home %}

            <div class="cell small-12 large-6">
                <div class="card" style="width: 100%;">
                    <img src="{{ entry.image.url }}">
                    <div class="card-section">
                      <h5><a href="{% url 'entry_app:detail_inputs' entry.id %}">{{ entry.title }}</a></h5>
                      <p>{{ entry.summary | truncatechars:60 }}</p>
                    </div>
                </div>
            </div>
                
            {% endfor %}
                
        </div>
        <!-- FIN bloque de blog principal -->
    </div>
    <!-- FIN del primer bloque home -->

    <!-- segundo bloque pantalla home -->
    <div class="grid-x align-center" style="margin-top: 1em;">
        <div class="cell small-12 large-10 callout secondary">
            <h3>{{ home.description }}</h3>
            <h5>{{ home.about_title }}</h5>
            <p>
                {{ home.about_text }}
            </p>

            <p>
                <button class="button" data-open="exampleModal2">Suscribirme</button>
            </p>

            <!-- This is the first modal -->
            <div class="reveal" id="exampleModal2" data-reveal style="width: 300px;">
                <p class="lead">Enter your email</p>
                <form class="grid-x grid-margin-x" method="POST" action="{% url 'home_app:add_suscriber' %}">{% csrf_token %}
                    <div class="cell small-12">
                        {{ form.email }}
                    </div>
                    <div class="cell small-12">
                        <button type="submit" class="success button">Subscribe</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
    <!-- FIN segundo bloque pantalla home -->


    <!-- tercer bloque home -->
    <div class="grid-x grid-margin-x align-center">
        <h3 class="cell">Recent Articles:</h3>

        {% for entry in entry_recent %}
            <div class="cell small-6 large-2">
                <div class="card" style="width: 100%;">
                    <img src="{{ entry.image.url }}" style="width: 300px;">
                    <div class="card-section">
                    <h4> <a href="{% url 'entry_app:detail_inputs' entry.id %}">{{ entry.title | truncatechars:30 }}</a></h4>
                    <p>{{ entry.summary | truncatechars:50 }}</p>
                    </div>
                </div>
            </div>

        {% endfor %}    
    </div>
    <!-- FIN tercer bloque -->
</div>
{% include "includes/footer.html" %}

{% endblock content %}