blog/applications/entry/urls.py
from django.urls import path
from . import views


app_name = "entry_app"

urlpatterns = [
    path('inputs/', views.EntryListView.as_view(), name='entry'), 
    path('detail-inputs/<slug>/', views.EntryDetailView.as_view(), name='detail_inputs')
]

blog/applications/favorite/urls.py
from django.urls import path
from . import views


app_name = "favorite_app"

urlpatterns = [
    path('profile/', views.UserPageListView.as_view(), name='profile'),
    # le pasamos un pk porque estamos recuperandolo en el entry= Entry.objects.get(id=self.kwargs['pk'])
    path('Add-entry/<pk>/',views.AddFavoriteView.as_view(), name='favorite_add'),
    path('delete-favorite/<pk>/', views.FavoriteDeleteView.as_view(), name='favorite_delete'),   
]

    

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
# Seo
from django.contrib.sitemaps.views import sitemap
from applications.home.sitemap import EntrySitemap, Sitemap

urlpatterns_main = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.entry.urls')),
    re_path('', include('applications.favorite.urls')),
    # url for ckeditor
    re_path(r'^ckeditor/',include('ckeditor_uploader.urls')),
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# site map object that generates xml
sitemaps={
    # url root
    'site':Sitemap(
        ['home_app:index']
    ),
    'entries': EntrySitemap

}

urlpatterns_sitemap=[
    path('sitemap.xml', sitemap,{'sitemaps':sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

# we concatenate the urlpatterns because it is the one who reads the urls.py
urlpatterns = urlpatterns_main + urlpatterns_sitemap

blog/applications/entry/models.py
from datetime import timedelta, datetime
#
from django.db import models
from django.conf import settings
from django.urls import reverse_lazy
from django.template.defaultfilters import slugify
#app third party
from model_utils.models import TimeStampedModel
from ckeditor_uploader.fields import RichTextUploadingField
#managers
from .managers import EntryManager


class Category(TimeStampedModel):
    short_name = models.CharField('Short name', max_length=15)
    name = models.CharField('Name', max_length=30)


    class Meta:
        verbose_name='Category'
        verbose_name_plural='Categories'

    def __str__(self):
        return self.name


class Tag(TimeStampedModel):
    """etiquetas de un articulo"""

    name = models.CharField('Name', max_length=30)

    class Meta:
        verbose_name='Label'
        verbose_name_plural='Tags'

    def __str__(self):
        return self.name

class Entry(TimeStampedModel):
    """modelo para entradas o articulo"""

    # con el AUTH_USER_MODEL hago referencia a nuestra clase User del models.py de la applications user 
    user= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    category= models.ForeignKey(Category, on_delete=models.CASCADE)
    tag=models.ManyToManyField(Tag)
    title = models.CharField('title',max_length=200)
    summary = models.TextField('Summary')
    content= RichTextUploadingField('Content')
    public = models.BooleanField(default=False)
    image = models.ImageField('Image', upload_to='Entry')
    cover_page = models.BooleanField(default=False)
    in_home= models.BooleanField(default=False)

    slug = models.SlugField(editable=False, max_length=300)

    objects= EntryManager()

    class Meta:
        verbose_name= 'Entry'
        verbose_name_plural= 'Inputs'

    def __str__(self):
        return self.title

    # Seo generate xml
    def get_absolute_url(self):
        return reverse_lazy(
            'entry_app:detail_inputs',
            kwargs={'slug':self.slug}
        )

    #generar el slug
    def save(self, *args, **kwargs):
        # calculamos el total de segundos de la hora actual
        now= datetime.now()
        total_time= timedelta(
            hours=now.hour,
            minutes=now.minute,
            seconds= now.second
        )
        seconds= int(total_time.total_seconds())
        slug_unique= '%s %s' % (self.title, str(seconds))

        self.slug= slugify(slug_unique)
        super(Entry,self).save(*args, **kwargs)

blog/applications/entry/views.py
from django.shortcuts import render

from django.views.generic import ListView, DetailView

from .models import Entry, Category

#blog
class EntryListView(ListView):
    template_name = "entry/list.html"
    context_object_name= 'entry'
    paginate_by= 3  

    def get_context_data(self, **kwargs):
        context = super(EntryListView, self).get_context_data(**kwargs)
        context['categories']= Category.objects.all()
        return context
    
    def get_queryset(self):
        kword= self.request.GET.get('kword','')
        category= self.request.GET.get('category','')
        # consulta  de busqueda
        result= Entry.objects.search_entry(kword, category)
        return result

#click al link y mostrar el contenido
class EntryDetailView(DetailView):
    template_name = "entry/detail.html"
    model = Entry
    context_object_name= 'entry_detail'

blog/templates/entry/base_entry.html
{% extends "base.html" %}

{% load  static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/myblog.css' %}">
{% endblock css %}

{% block js %}

{% endblock js %}

blog/templates/entry/detail.html
<!-- head para PC -->
{% extends "entry/base_entry.html" %}
{% load  static %}

<!-- entry_detail viene del views.py del context_object_name de la clase EntryDetailView y title del models.py de entry-->
{% block title %}
{{ entry_detail.title }}  
{% endblock title %}

{% block description %}
<meta name="description" content="{{ entry_detail.summary }}"> 
{% endblock description %}


{% block tags %}
<meta name="keywords" content="
{% for t in entry_detail.tag.all %}
    {{ t.name }}
{% endfor %}
"> 
{% endblock tags %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x grid-margin-x" style="margin-top: 1em;">
        <h3 class="cell">{{ entry_detail.title }}</h3>

        <!-- bloque de contenido del articulo -->
        <div class="cell large-8">
            <div class="cell callout primary">
                <h5>Summary:</h5>
                <p>{{ entry_detail.summary }}</p>
            </div>
            <div>
                <p>{{ entry_detail.content | safe }}</p>
            </div>
        </div>
        <!-- FIN bloque contenido del articulo -->

        <!-- bloque llamada a la accion -->
        <div class="cell large-4">
            <div class="card" style="width: 100%;">
                <img src="{% static 'img/logo_favorite.PNG' %}"  style="width: 250px; align-self: center;">
                <div class="card-section" style="width: 100%;">
                  <form class="blog-action" method="POST" action="{% url 'favorite_app:favorite_add' entry_detail.id %}">{% csrf_token %}
                    <button type="submit" class="button alert">Add to favorites</button>
                  </form>
                </div>
            </div>
        </div>
        <!-- FIN bloque llamada a la accion -->
    </div>
</div>
{% include "includes/footer.html" %}

{% endblock content %}

blog/templates/entry/list.html
<!-- head para PC -->
{% extends "entry/base_entry.html" %}

{% load  static %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x grid-margin-x" style="margin-top: 2em;">
        <!-- primer bloque pantalla blog -->
        <div class="cell small-10 large-8">

            <!-- bloque de buscador -->
            <form class="input-group" method="GET">{% csrf_token %}
                <input class="input-group-field" type="text" id="kword" name="kword" placeholder="Search">
                <div class="input-group-button">
                  <input type="submit" class="button" value="Search">
                </div>
            </form>
        
            <!-- FIN bloque de formulario -->

            <!-- inicio bloque de resultados de busqueda -->  
            <div class="grid-x grid-margin-x ">
                {% for inputs in entry %} <!--entry viene del context_object_name= 'entry'-->
                    <div class="cell">
                        <div class="card" style="width: 100%;">
                            <img src="{{ inputs.image.url }}" style="width: 300px;">
                            <div class="card-section">
                                <h4> <a href="{% url 'entry_app:detail_inputs' inputs.slug %}">{{ inputs.title | truncatechars:30 }}</a></h4>
                                <p>{{ inputs.summary | truncatechars:50 }}</p>
                            </div>
                        </div>
                    </div>
                </div>
                {% empty %}
                <h3 style="color: red;"> No result found</h3>
                {% endfor %}
                    
            <!-- FIN bloque de resultados de busqueda -->
        </div>
        <!-- FIN primer bloque pantalla blog -->
        

        <!-- inicio del segundo bloque - categorias -->
        <div class="cell small-12 large-4" style="height: 500px;">
            <div class="card-section">
                <h4>Categories</h4>
                <ul class="vertical menu">
                    
                    {% for category in categories %}
                        <li><a href="?category={{ category.short_name }}">{{ category.name }}</a></li>
                    {% endfor %}

                </ul>
            </div>
        </div>
        <!-- FIN inicio del segundo bloque - categorias -->
    
    </div>

    <!-- inicio de bloque de paginacion -->
    <div class="cell">
        {% if is_paginated %}
           <nav aria-label="Pagination">
               <ul class="pagination text-center">        
                   {% if page_obj.has_previous %}
                       <li class="pagination-previous"><a href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                   {% endif %}
                   
                   {% for pages in paginator.page_range %} <!--paginator es paginate_by de mi views.py-->

                       {% ifequal pages page_obj.number %} <!-- ifequal hace comparaciones--> 
                           <li class="current"><span class="show-for-sr">You're on page</span>{{ pages }}</li>
                       {% else %}
                           <li><a href="?page={{ pages }}">{{ pages }}</a></li>    
                       {% endifequal %}
                           
                   {% endfor %}
                     
                   {% if page_obj.has_next %}
                       <li class="pagination-next"><a href="?page={{ page_obj.next_page_number }}">Next</a></li>
                   {% endif %}
               </ul>
           </nav>
       {% endif %}
    </div>
    <!-- FIN bloque de paginacion -->
</div>
{% include "includes/footer.html" %}

{% endblock content %}